Tagging varivoda
sbtqa/cucumber-runner pull request #2
Opened 2017-04-21 15:58 UTC by clicman

2017-04-24 03:18 UTC, kosteman requested changes

2017-04-24 03:18 UTC, kosteman commented on pom.xml
> +      <!--<plugin>-->
uncomment this block

2017-04-26 03:43 UTC, kosteman approved these changes

2017-05-04 06:13 UTC, 0I0u3uk approved these changes

2017-05-04 06:30 UTC, merged