Override method result() for catch RuntimeExcption
sbtqa/cucumber-runner pull request #7
Opened 2017-09-11 11:56 UTC by imixac

2017-09-11 12:18 UTC, clicman requested changes

2017-09-11 12:18 UTC, clicman commented on src/main/java/ru/sbtqa/tag/allure/TagAllureReporter.java
> +//    Добавил обработку RuntimeException
Only English plz

2017-09-11 12:18 UTC, clicman commented on src/main/java/ru/sbtqa/tag/allure/TagAllureReporter.java
> +//    @Override
Why is Override commented out?

2017-09-11 12:18 UTC, clicman commented on src/main/java/ru/sbtqa/tag/allure/TagAllureReporter.java
> +//    Но мне кажется это бред, потому что private нельзя оверайдить
Use javadoc capable comment for method

2017-09-11 12:18 UTC, clicman commented on src/main/java/ru/sbtqa/tag/allure/TagAllureReporter.java
> +//    Саму ошибку решил тут обрабатывать
Remove this comment

2017-09-11 12:18 UTC, clicman commented on src/main/java/ru/sbtqa/tag/allure/TagAllureReporter.java
> +//    Но мне кажется это бред, потому что private нельзя оверайдить
Agree.

2017-09-21 07:17 UTC, kosteman commented on src/main/java/ru/sbtqa/tag/allure/TagAllureReporter.java
> +                return result.getError().getCause();
too many tabs

2017-09-21 07:17 UTC, kosteman commented on src/main/java/ru/sbtqa/tag/allure/TagAllureReporter.java
> +    public Throwable getError(Result result){
add space between ) and {

2017-09-21 11:24 UTC, imixac commented
@kosteman allure-cucumberjvm merged
check pull request

2017-09-21 11:25 UTC, clicman commented
We should wait for release.

чт, 21 сент. 2017 г. в 18:24, imixac <notifications@github.com>:

> @kosteman <https://github.com/kosteman> allure-cucumberjvm merged
> check pull request
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/sbtqa/cucumber-runner/pull/7#issuecomment-331128453>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABB4756205v_Bdswa_maiCxIdomyWVHoks5skkdtgaJpZM4PTDBT>
> .
>

2017-09-21 15:16 UTC, clicman commented
http://central.maven.org/maven2/ru/yandex/qatools/allure/allure-cucumber-jvm-adaptor/1.6.4/
Released

2017-09-21 15:17 UTC, clicman commented
@imixac  update pom.xml to 1.6.4

2017-09-25 09:20 UTC, merged